opensource-observer/oss-directory

README.md
package.json
pnpm-lock.yaml
src/fetchData.ts
src/index.ts

* Include a `fetchData` function for cloning the repo into a temporary directory and read all the data via TS/JS
* Update README to show users how to use it

feat: fetchData

---

src/scripts/optimism-attestation.ts
src/utils/common.ts
src/utils/error.ts

* Fix compiler bugs, minor reorganization

fix: just some minor cleanup

---

data/projects/e/ethereum-attestation-service.yaml
data/projects/g/gnosis-safe.yaml
data/projects/readme.md
data/projects/s/sound-xyz.yaml

*  new: EAS
*  update: (gnosis) safe
*  update: sound.xyz

data updates

---

data/projects/i/ipfs.yaml

These represent independent implementations of the IPFS protocol

Add new URLs to ipfs.yaml

---

data/projects/g/growthepie.yaml

Hey all,
We are trying to be consistent with our naming on all platforms. No upper case, no space. 
Would be great to merge this - thank you for all your work!

Update growthepie name

---

data/projects/s/synapse.yaml

Added the Synapse router npm package to qualify Synapse for the "Popular Packages" Category

Add NPM package

---

src/fetchData.ts
src/index.ts

This adds a loadData command I need to load two different versions of the directory

Add `loadData`

---

.github/workflows/setup-external-pr-tools/action.yml
data/projects/r/rhino.yaml

Work to get workflows working. Autogenerated body.

Workflow fix 

---

.github/workflows/ci-default.yml
.github/workflows/setup-external-pr-tools/action.yml
pnpm-lock.yaml

- Update to use the correct pnpm version
- Update pnpm lock
- clean

Fix PNPM Version

---

src/resources/schema/blockchain-address.json
src/types/blockchain-address.ts
src/types/project.ts

* Also alphabetize the networks in the schema

fix: add metal network

---

data/projects/k/kleros.yaml

add: Kleros project (#283)

---

data/projects/r/rabbithole.yaml
data/projects/v/velodrome.yaml
data/projects/z/zora.yaml

- Velodrome (Base)
- Rabbithole (Base)
- Zora (Base, Zora)

add test deployers

---

data/projects/m/mcgingras-loot2.yaml

Let me know if this looks okay, thanks!

Adds loot2

---

.github/workflows/external-prs-handle-comment.yml
.github/workflows/validate-pr-owners.yml
.github/workflows/validate/action.yml

* Includes fix to not run for contributors

fix: GitHub app env variables include Base validators

---

data/projects/0/0x-splits.yaml

Adding way more contract addresses and updating a couple that were already there. Please lmk if anything is formatted wrong. Thanks!

Update 0xSplits entry with new data

---

data/projects/c/compound-finance.yaml

Hey.
The purpose of this PR is to verify that 0x2501713A67a3dEdde090E42759088A7eF37D4EAb address was a deployer of 0x7e7d4467112689329f7E06571eD0E8CbAd4910eE using Optimism Bridge.
In the optimistic scan, we see that our address 0x2501713A67a3dEdde090E42759088A7eF37D4EAb has deployed COMP token https://optimistic.etherscan.io/address/0x7e7d4467112689329f7E06571eD0E8CbAd4910eE#internaltx, however, we deployed it via this contract - https://optimistic.etherscan.io/address/0x4200000000000000000000000000000000000012

Update Compound.finance on Optimism

---

data/projects/g/giveth.yaml

add addresses for GIVx and some EOA deployer keys and fund handlers

add missing giveth addresses

---

data/projects/s/socket-tech.yaml
data/projects/s/socket.yaml

This PR updates the details about socket.
- new npm packages
- fix links and description
- latest contract and deployer addresses

Socket details fix

---

data/projects/s/stargate-finance.yaml

Adding all Base Contracts for OP Retro Funding

Update stargate-finance.yaml with Base Contracts

---

package.json
pnpm-lock.yaml
src/actions/transform.ts
src/resources/schema/project.json
src/resources/schema/social-profile.json
src/transformations/importAgora.ts
src/transformations/index.ts
src/types/project.ts
src/types/social-profile.ts

* This heavily encodes certain assumptions about the CSV format. Might need to be updates if they ever change that format

feat: transformation that imports a CSV file from Agora

---

data/projects/p/paraswap.yaml

Update paraswap.yaml: Adding Base

---

data/projects/e/elimu-ai.yaml

Update project data for existing project with unique identifier `elimu-ai`
- Add project description
- Add blockchain addresses

update project data: elimu-ai.yaml

---

data/projects/a/archlyfi.yaml
data/projects/c/compound-finance.yaml
data/projects/f/fractal-visions.yaml
data/projects/o/orderlynetwork.yaml
data/projects/w/woonetwork.yaml

Project | Address | Network | Action
-- | -- | -- | --
compound-finance | 0xb125e6687d4313864e53df431d5425969c15eb2f | BASE | Contract included in application and should be added to OSS Directory; previously had been tracked via its deployer.
fractal-visions | 0xb50875d250fca66775f7b6c2cc4e79cd8cbbba34 | OPTIMISM | Contract included in application and should be added to OSS Directory; previously had been tracked via its deployer.
archlyfi | 0x193a2d15a9a8fa02301116d4f3666619154beeb7 | FRAX | Contract included in application and should be added to OSS Directory; deployment on Frax was missed at the time of application.
woonetwork | 0x816f722424b49cf1275cc86da9840fbd5a6167e9 | BASE; OPTIMISM | Contract had been attributed to woofi in OSS Directory before the round; should only be credited …

updates contracts in 2024-07-02 changelog

---

src/ossdirectory/clone.py
src/ossdirectory/fetch.py

small fixes that helped me run the python library more stable on Windows

specify encoding, close temporary file handle

---

data/projects/g/givestation.yaml
data/projects/p/passportxyz.yaml

twitter should go under socials

fix correct format of 2x yaml projects

---

data/projects/b/blob-archiver-rs.yaml

add: new project blob-archiver-rs

---

data/projects/d/dispute-explorer.yaml

add: new project dispute-explorer

---

data/projects/b/boregon-trail-thebreadcast.yaml
data/projects/b/boregon-trail.yaml

Adding in Boregon Trail game into OSS.  Please let me know if there are any questions.  Thanks in advance!

adding boregon-trail into OSS

---

data/collections/protocol-guild.yaml

Adding the following:
- https://github.com/ethereum/go-verkle
- https://github.com/Consensys/teku
- https://github.com/Prysmaticlabs/Prysm
- https://github.com/paradigmxyz/reth
- https://github.com/ethereum/beacon-APIs/
- https://github.com/ethereum/protocol-security/
Removed the following:
- ethereum-org-website-ethereum

Update Protocol Guild's projects

---

data/projects/z/zenbiteth.yaml

- Added 2 more website links
- Added 2 contract addresses deployed on optimism mainnet
- Added few more repo links
- Update social links

Zenbit: Add links and contract addresses

---

data/projects/c/cookie3.yaml
data/projects/d/doodles-app.yaml
data/projects/g/gameswift.yaml
data/projects/o/open-runes.yaml
data/projects/r/raventrammell.yaml
data/projects/s/stix-protocol.yaml
data/projects/x/xsaiyan-tech.yaml

7 projects added (#9)

---

data/projects/m/moxie.yaml

Hi team,
Raising a new PR to add [Moxie Protocol](https://moxie.xyz/) and it's deployer addresses.
Please let me know if there are any issues or questions
Cheers,
Ignas

adding moxie

---

data/projects/b/blur-io.yaml
data/projects/d/draculafi.yaml
data/projects/m/maestro-bots.yaml
data/projects/n/nile-exchange.yaml
data/projects/p/poolshark.yaml
data/projects/p/pudgy-world.yaml
data/projects/s/space-id.yaml
data/projects/v/vooi.yaml
data/projects/z/zkdx.yaml
data/projects/z/zora-aio.yaml

Restore branch (#10)

---

data/projects/b/babel.yaml
data/projects/e/eslint.yaml
data/projects/f/facebook-oss.yaml
data/projects/h/homebrew.yaml
data/projects/j/julia-lang.yaml
data/projects/n/numpy.yaml
data/projects/o/open-web-docs.yaml
data/projects/p/pandas.yaml
data/projects/p/pnpm.yaml
data/projects/w/webpack.yaml

See https://github.com/opensource-observer/oso/issues/2314

fix(ossd): move open collective artifacts to websites field

---

data/projects/e/evaluating-voting-design-tradeoffs-for-retro-funding-govxs.yaml
data/projects/g/govxs.yaml

This PR adds the project "Evaluating Voting Design Tradeoffs for Retro Funding" to the OSS Directory. The project is hosted at https://github.com/GovXS/Evaluating-Voting-Design-Tradeoffs-for-Retro-Funding and evaluates tradeoffs in voting mechanisms for retroactive funding.
Artifacts added:
https://github.com/GovXS/Evaluating-Voting-Design-Tradeoffs-for-Retro-Funding

Add project Evaluating Voting Design Tradeoffs for Retro Funding

---

data/projects/a/anchain-ai.yaml
data/projects/k/kata-games.yaml

Added anchain-ai and kata-games

Created two new projects from Stellar funding data

---

data/projects/b/blast-io.yaml
data/projects/c/chiliz.yaml
data/projects/c/cowprotocol.yaml
data/projects/d/dop-org.yaml
data/projects/e/ethena-labs.yaml
data/projects/o/omniaprotocol.yaml
data/projects/p/puffer-fi.yaml
data/projects/s/starknet-io.yaml
data/projects/x/xterio.yaml

Restore (#12)

---

data/projects/b/bitget.yaml
data/projects/d/decentraland.yaml
data/projects/e/eclipse-xyz.yaml
data/projects/e/ethcoin-org.yaml
data/projects/f/fetchai.yaml
data/projects/f/fuellabs.yaml
data/projects/i/immutable.yaml
data/projects/k/kraken.yaml
data/projects/k/kucoin.yaml
data/projects/l/l3e7-io.yaml
data/projects/m/manta-network.yaml
data/projects/m/mavia-gg.yaml
data/projects/m/mon-protocol.yaml
data/projects/o/ondoprotocol.yaml
data/projects/s/singnet.yaml
data/projects/y/yugalabs.yaml
data/projects/z/zircuit-labs.yaml

bitget.yaml
decentraland.yaml
fetchai.yaml
eclipse-xyz.yaml
yugalabs.yaml
ethcoin-org.yaml
fuellabs.yaml
immutable.yaml
kraken.yaml
kucoin.yaml
l3e7-io.yaml
manta-network.yaml
mavia-gg.yaml
mon-protocol.yaml
ondoprotocol.yaml
singnet.yaml
zircuit-labs.yaml

17 projects added (#15)

---

src/validator/index.ts

See https://github.com/nodejs/node/issues/51622

fix: as of Node 22, JSON imports happen with `with`

---

README.md
package.json
pyproject.toml
src/types/named.ts
src/types/project.ts

* Added the repository and website to pyproject.toml

feat: bump version numbers for publish to npm/pypi

---

data/collections/ethereum-crypto-ecosystems.yaml
data/projects/u/uniswap.yaml
data/projects/u/uniswapfoundation.yaml

- **delete duplicate 'uniswapfoundation'**
- **fix: uniswapfoundation in collection file**

fix: uni duplicate

---

package.json
pyproject.toml
src/resources/schema/project.json
src/types/project.ts

* Bump npm and pypi version numbers and published

feat: add defillama URLs to project schema

---

data/projects/b/bridgers.yaml
data/projects/d/dydx.yaml
data/projects/e/ethervista.yaml
data/projects/m/mexc.yaml
data/projects/m/museumofcryptoart.yaml
data/projects/n/nillion.yaml
data/projects/s/soneium.yaml
data/projects/t/titanx-win.yaml
data/projects/w/well3.yaml

9 projects added

---

data/projects/c/callthis-shazow.yaml
data/projects/c/callthis.yaml

Hi there, adding one of my projects that's not indexed yet: https://github.com/shazow/callthis

add callthis

---

data/projects/c/create2deployer.yaml

Add `create2deployer` to Open Source Observer

---

data/projects/x/xdeployer.yaml

Add `xdeployer` to Open Source Observer

---

data/projects/h/host-it.yaml

This PR adds **HostIT**, a web3 event ticketing platform with integrated POAP functionality, to the OSS Directory. The entry includes comprehensive details about the project, its social channels, GitHub repository, and relevant blockchain addresses.  
---
**HostIT** is a decentralized event ticketing solution leveraging blockchain technology to combat ticket fraud and streamline event management for organizers and attendees in the web3 ecosystem.  
---
- **Website**: [hostit.events](http://hostit.events)  
- **Social Media**:  
- Twitter: [@hostit_events](https://twitter.com/hostit_events)  
- Telegram: [HostIT Community](https://t.me/hostitevents)  
- **GitHub Organization**: [hostit-events](https://github.com/hostit-events)  
---
1. **Deployer Address (EVM Chains)**  
- Address: …

Add HostIT to OSS Directory

---

data/projects/a/aragon.yaml

Add Aragon [ve-governance](https://github.com/aragon/ve-governance) contracts.
- Escrow & Voter for MODE and BPT
- Escrow & Voter for KIM and xKIM

Add Aragon veGov contracts

---

data/projects/e/ethereum-attestation-service.yaml
data/projects/p/pyth-network.yaml

- **fix: pyth-network dups**
- **add eas predeploys**

fix: pyth and eas predeploys

---

data/projects/f/fidlabs.yaml
data/projects/s/smallbraingames.yaml
data/projects/t/tomo-socials.yaml

- **fix: fidlabs website**
- **fix: tomo-social description**
- **fix: smallbraingames description**

fix: invalid artifact elements

---

data/projects/b/brahma.yaml

This PR updates `./data/projects/b/brahma.yaml` to add brahma's console core contracts, and removes older legacy contracts.

brahma console contracts

---

data/collections/filecoin-core.yaml

These came up on a talk with Juan as the initial list feels that doens't cover the entire "Core".

Update filecoin-core collection projects

---

data/projects/p/panoptic-labs.yaml

changed display name to Panoptic labs

disp name: Panoptic Labs

---

data/collections/arbitrum-crypto-ecosystems.yaml
data/collections/base-crypto-ecosystems.yaml
data/collections/ethereum-crypto-ecosystems.yaml
data/collections/polygon-crypto-ecosystems.yaml
data/collections/scroll-crypto-ecosystems.yaml
data/projects/a/arcadexyz.yaml
data/projects/e/ergopad.yaml
data/projects/h/harvest-finance.yaml
data/projects/h/harvestfi.yaml
data/projects/m/minimaxdefi.yaml
data/projects/m/minimaxfinance.yaml
data/projects/p/project-serum.yaml
data/projects/p/pwnfinance.yaml
data/projects/r/railgun-community.yaml
data/projects/r/railgun-privacy.yaml
data/projects/t/tokenbankteam.yaml
data/projects/t/tp-lab.yaml

- **prep for defillama sync**
- **add slugs**

add: initial scan of defillama projects

---

data/projects/a/authgear.yaml

This PR adds Authgear, an open-source alternative to Auth0.

Add Authgear

---

data/projects/j/juz-mini-app.yaml

Adds https://github.com/D3Portillo/mini-juz to the directory

Adding juz-mini-app.yaml

---

data/projects/c/createmytoken.yaml

Adds newer contracts, now a full e2e system.

Update CMT Platform

---

data/projects/a/aestra.yaml

Create aestra.yaml for Aestra Finance project

---

data/collections/arb-stylus.yaml
data/projects/9/9lives-fluidity-money.yaml
data/projects/a/af-afk-stylus.yaml
data/projects/m/microstable-stylus-jacksmithinsulander.yaml
data/projects/s/stylus-developers-guild.yaml

- **add: new projects**
- **fix: update stylus collection to include fluidity (and drop 9lives dupe)**

fix: fixes fluidity and adds additional projects

---

data/projects/f/fiat24.yaml

Added details about the Fiat24 fintech platform including its description, website, and social media link.

Add Fiat24 project details to fiat24.yaml

---

data/projects/b/beacon-labs.yaml
data/projects/b/beaconlabs-io.yaml

[Beacon Labs(prev Fracton Research](https://beaconlabs.io) is an R&D institution for a positive sum world through exploring inclusive coordination design.

Add new project configuration for Beacon Labs

---

data/projects/i/icecreamswap.yaml

IceCreamSwap is a multichain DeFi platform offering various features including swap, liquidity, staking, bridging, and a launchpad.

Add icecreamswap.yaml configuration file
