opensource-observer/oss-directory

- src/actions/validate.ts
- src/scripts/decouple-optimism-json.ts
- src/utils/format.ts
* Add generic path formatting tools to get the path to a project or collection file
* Update collection validation logic to also enumerate through projects and make sure those files exist
> feat: validate collections now also checks if each project slug exists

- data/projects/g/gitcoin-grants-data-portal-davidgasquez.yaml
- data/projects/s/supermodular-xyz.yaml
Testing community [workflow](https://github.com/opensource-observer/oss-directory/issues/170) for tracking new repositories, adds one user-owned project and one Github org to tracking list. 
Ideally anyone would prefer if those were submitted in bulk, but I am following @ccerv1 to start small to see if I am getting the schema right.
|Entity|Count|Rate|
| --- |---| ---|
| Projects | 2 | 1 USDC |
| Wallet Address| 1 | 0.50 USDC |
| Github Repository | 1 | 0.10 USDC|
| Github Org URL | 1 | 0.50 USDC|
> Add supermodular + data portal

- src/scripts/update_project.py
I had to monkeypatch this when trying to apply this function as `project_path` does not seem to be defined anywhere within function body.
> fix: tweak variable name

- package.json
- src/fetchData.ts
When I ran this test locally, it was already in the git directory so it didn't fail (that was a special scenario). This should address that.
> Fix git branch checkout

- README.md
- package.json
- src/fetchData.ts
- src/validator/index.ts
* JSON schema has changed, we need to publish with latest migration
* Added a reminder in the README for next time
* Added a pathway to skip validation when reading files, though we don't use that
> fix: publish the latest schemas

- data/projects/a/aave.yaml
Add the deployer addresses of the ACI (Aave Chan Initiative) to `aave.yaml`:
- [0x57ab7ee15cE5ECacB1aB84EE42D5A9d0d8112922](https://etherscan.io/address/0x57ab7ee15cE5ECacB1aB84EE42D5A9d0d8112922): deployer 22
- [0x329c54289Ff5D6B7b7daE13592C6B1EDA1543eD4](https://etherscan.io/address/0x329c54289Ff5D6B7b7daE13592C6B1EDA1543eD4): deployer 13
- [0x3Cbded22F878aFC8d39dCD744d3Fe62086B76193](https://etherscan.io/address/0x3Cbded22F878aFC8d39dCD744d3Fe62086B76193): deployer 21
> Add ACI deployers to aave addresses list

- data/projects/a/aerodrome-finance.yaml
- data/projects/v/velodrome.yaml
Adding Velodrome and Aerodrome contracts
`any_evm` was used for contracts deployed to BOB chain. Please lmk if I should remove those contracts
> add: velodrome, aerodrome contracts

- data/projects/c/createmytoken.yaml
@akshatmittal I have run some tests on the production data and am now seeing the issue you alerted me to in your initial PR #332 
Unfortunately, we won't be able to attribute the downstream impact of these deployments to CMT. The attribution requirements for this round are very strict: all impact goes to the owner of the deployer. 
FWIW, this requirement has caused some disappointment with other use cases 😞  (eg, apps that facilitate P2P transactions, interactions with zora factories, etc)
In any case, I have kept the other deployments you included, but removed the multicall and create2 contracts from the CMT project file.
> fix: remove multicall and create2 from CMT

- data/projects/t/The-book-of-optimism-fault-proof.yaml
- data/projects/t/the-book-of-optimism-fault-proof-joohhnnn.yaml
Hi there Im not sure if there is a tag named fault proof. If not, PLZ delete it.
> add: new project The-book-of-optimism-fault-proof

- data/collections/open-collective.yaml
- data/projects/b/babel.yaml
- data/projects/e/eslint.yaml
- data/projects/f/facebook-oss.yaml
- data/projects/h/homebrew.yaml
- data/projects/j/julia-lang.yaml
- data/projects/n/numpy.yaml
- data/projects/o/open-web-docs.yaml
- data/projects/p/pandas.yaml
- data/projects/p/pnpm.yaml
- data/projects/w/webpack.yaml
- src/resources/schema/project.json
This PR introduces data for the ten most notable (entirely subjective) Open Source Software projects in Open Collective. It also adds an `open_collective` field for projects within the project schema. This is part of https://github.com/opensource-observer/oso/issues/2200.
> add: open collective top `10` projects

- .github/workflows/external-prs-handle-comment.yml
- .github/workflows/validate-pr-owners.yml
This PR updates the permissions checks for workflow steps. Previously, important steps like `validate` were executed when the user had the roles `OWNER`, `MEMBER`, or `COLLABORATOR`. Now, these steps will only run if the user is an `admin` as defined by the `oso` PR tools, aligning with the permissions model in the `oso` repository. This change ensures consistency in permissions across the project.
> fix: update `workflow` permissions

- .github/workflows/external-prs-handle-comment.yml
- .github/workflows/validate-pr-owners.yml
This PR addresses an oversight where the path for the oso tools was incorrectly configured. The changes ensure that the tools are now correctly set up.
> fix: oso workflow `tools` path

- .github/workflows/external-prs-handle-comment.yml
- .github/workflows/validate-pr-owners.yml
This reverts the last two commits to restore functionality while troubleshooting an issue with workflow execution. For details, see [this run](https://github.com/opensource-observer/oss-directory/actions/runs/11150794261/job/30992769940).
> fix: revert `workflow` permissions fix

- src/resources/schema/project.json
* As discussed, we'll stick to URLs, which will make future validation easy (check for 404s)
* Downstream pipelines will need to extract names from the URL
> feat add cargo, go, and pypi to project.json

- package.json
- pyproject.toml
- src/resources/schema/project.json
- src/types/project.ts
* Looks like we've been using crates all this time, but didn't notice that it didn't match the schema.
* Updated the schema to reflect this
* Published new versions to npm/pypi
> fix: rename cargo => crates in the schema

- src/actions/validate.ts
* Since the validator was written, we've added new project fields.
* This will check for URL conflicts between files
* It is okay to have duplicates within a single file (e.g. in `go` and `github`)
> fix: check for URL conflicts across more project fields

- data/projects/o/open-uem.yaml
- data/projects/o/openuem.yaml
I'd like to add openuem to your OSS directory
Thanks in advance!
> feat: add openuem project

- .github/workflows/external-prs-handle-comment.yml
This PR uses the correct event type for the `handle-comment` CI workflow.
> fix: use correct `event` payload

- .github/workflows/external-prs-handle-comment.yml
This PR fixes the validate PR comment logic to actually check whether the comment author is the admin, not the issue author.
> fix: check whether the comment `author` is admin

- data/projects/a/aave.yaml
- data/projects/k/kelp-dao.yaml
- data/projects/p/pancakeswap.yaml
- src/actions/validate.ts
This PR fixes #690 by removing the invalid slugs and adding logic to validate Defillama protocol URLs when running `pnpm run validate`.
> fix: remove `invalid` defillama slugs

- src/actions/defillama.ts
- src/actions/validate.ts
- src/cli.ts
This PR adds a new subcommand `validate-defillama-slugs`, which validates all Defillama slugs in oss-directory to check if they're valid.
>  fix: decouple `defillama` validation from project validation

- data/projects/w/wieldlabs.yaml
Our ["Club Coin" x Farcaster](https://far.club) project uses a deployer for new "Club Coin" drops, so we cannot directly verify ownership in Optimism Retro Grants. I'm adding the deployer to OSS, which is located at [0x0e013e88a8b94ca85ee8e0c11b0899e4556bff1e](https://basescan.org/address/0x0e013e88a8b94ca85ee8e0c11b0899e4556bff1e) - ideally this should include the [NFT collection](https://opensea.io/collection/clubcoin) deployed at [0x2087dd5c0b093340c35357ba014a401ee9b16ab1](https://basescan.org/address/0x2087dd5c0b093340c35357ba014a401ee9b16ab1) automatically, thanks!
We also have a [FarTokenFactory](https://basescan.org/address/0x5c4743942072d2d0772b9887770e0943a67af6b4#code) for [FarTokens](https://far.quest/tokens).
You can view our attestation on Optimism to see I [deployed the …
> Update wieldlabs with ClubCoinDropFactory, FarTokenFactory

- data/projects/p/panoptic-labs.yaml
The panoptic-labs.yaml file was added in the past. We weren't aware and made a new submission for Panoptic here: https://github.com/opensource-observer/oss-directory/pull/734
We'd like to replace the old panoptic file now, and just use the new one - current version here: https://github.com/opensource-observer/oss-directory/blob/main/data/projects/p/panoptic.yaml
> fix: remove Panoptic duplicate

- data/projects/m/magpieprotocol.yaml
Kept the same file name and only changed the display name and description as suggested in the last PR which is closed: https://github.com/opensource-observer/oss-directory/pull/794
> Rebrand Magpie Protocol to fly trade
